services:
  sample_tfrecord:
    container_name: sample_tfrecord
    image: sample_tfrecord
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - TF_CPP_MIN_LOG_LEVEL=2
    stdin_open: true  
    tty: true       
